// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application"

import "./light_editor_controller";
import "./standard_editor_controller";
import "./empty_html_field_controller";
