plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - config/routes.rb
    - db/seeds/**
    - db/seeds_*
    - db/schema.rb
    - tmp

Style/Documentation:
  Enabled: false
