services:
  db:
    image: postgres
    volumes:
      - hysperial_book_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=hysperial_book_development
      - PGDATA=/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true  # along with the memlock settings below, disables swapping
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m  # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=hysp3rial_bOOk    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and higher
      - DISABLE_INSTALL_DEMO_CONFIG=true # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - DISABLE_SECURITY_PLUGIN=true # Disables Security plugin
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - hysperial_book_opensearch_data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600  # required for Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
     - opensearch

  redis:
    image: "redis:alpine"
    environment:
      - REDIS_REPLICATION_MODE=master

  web:
    build: .
    environment:
      - RAILS_ENV=development
      - APP_DATABASE_NAME=hysperial_book_development
      - APP_DATABASE_USERNAME=docker
      - APP_DATABASE_PASSWORD=docker
    volumes:
      - .:/app
      - hysperial_book_yarn_cache:/root/.yarn-cache
    ports:
      - "3000:3000"
    depends_on:
      - db
      - opensearch
      - redis

  adminer:
    image: adminer
    restart: always
    ports:
      - "3001:8080"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  hysperial_book_data: ~
  hysperial_book_index: ~
  hysperial_book_yarn_cache: ~
  hysperial_book_opensearch_data:
