// JsFromRoutes CacheKey 91e53f62d7b1260d6ed032f054c5b9ac
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  search: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tags/search'),
  index: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tags'),
  create: /* #__PURE__ */ definePathHelper('post', '/bookcase/content_tags'),
  new: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tags/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tags/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tags/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/content_tags/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/content_tags/:id'),
}
