// JsFromRoutes CacheKey 8f06c39f81eff7d6907fc50a5c734f98
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/documents'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/documents/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/documents/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/media/documents/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/media/documents/:id'),
}
