// JsFromRoutes CacheKey 079bf152896e4f4c27a3361cf6594437
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/pictures'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/pictures/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/pictures/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/media/pictures/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/media/pictures/:id'),
}
