// JsFromRoutes CacheKey f67235e3da85f7d591ffd8782c5fee90
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/scans'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/scans/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/bookcase/media/scans/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/media/scans/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/media/scans/:id'),
}
