// JsFromRoutes CacheKey 6784c19d0fa0b1e8f58a4837f5ed7319
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  search: /* #__PURE__ */ definePathHelper('get', '/bookcase/books/:book_id/contents/search'),
  index: /* #__PURE__ */ definePathHelper('get', '/bookcase/books/:book_id/contents'),
}
