// JsFromRoutes CacheKey a8b6f02f9923373ca1a0a9298e26ab1f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  search: /* #__PURE__ */ definePathHelper('get', '/bookcase/contents/search'),
  editMode: /* #__PURE__ */ definePathHelper('post', '/bookcase/contents/:id/edit_mode'),
  index: /* #__PURE__ */ definePathHelper('get', '/bookcase/contents'),
  create: /* #__PURE__ */ definePathHelper('post', '/bookcase/contents'),
  new: /* #__PURE__ */ definePathHelper('get', '/bookcase/contents/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/contents/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/bookcase/contents/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/contents/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/contents/:id'),
}
