// JsFromRoutes CacheKey fc9e2aeff6b0c9bc0afc569bfba10361
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/bookcase/content_taggings'),
  new: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_taggings/new'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/content_taggings/:id'),
}
