// JsFromRoutes CacheKey bc0be9834711bacdccf16a5aaa3cf51b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  search: /* #__PURE__ */ definePathHelper('get', '/bookcase/books/search'),
  index: /* #__PURE__ */ definePathHelper('get', '/bookcase/books'),
  create: /* #__PURE__ */ definePathHelper('post', '/bookcase/books'),
  new: /* #__PURE__ */ definePathHelper('get', '/bookcase/books/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/books/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/bookcase/books/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/books/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/books/:id'),
}
