// JsFromRoutes CacheKey 351168bdd499d0337cb49424d884be6d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/bookcase/akin_content_tags'),
  new: /* #__PURE__ */ definePathHelper('get', '/bookcase/akin_content_tags/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/akin_content_tags/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/akin_content_tags/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/akin_content_tags/:id'),
}
