// JsFromRoutes CacheKey 2189dcf4a96599b5fe9baa993640b8d0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  search: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tag_families/search'),
  index: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tag_families'),
  create: /* #__PURE__ */ definePathHelper('post', '/bookcase/content_tag_families'),
  new: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tag_families/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tag_families/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_tag_families/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/content_tag_families/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/content_tag_families/:id'),
}
