// JsFromRoutes CacheKey aade1d52d0978d3c2334dff878d36bc0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/bookcase/content_attributes'),
  new: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_attributes/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/bookcase/content_attributes/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/bookcase/content_attributes/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/bookcase/content_attributes/:id'),
}
